# Generated by Django 5.0.9 on 2026-09-20 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('news', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIEW', 'Visualizacao'), ('CLICK', 'Clique'), ('SHARE', 'Compartilhamento'), ('FAVORITE', 'Favorito'), ('READ_TIME', 'Tempo de leitura')], db_index=True, max_length=10)),
                ('sessao', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rotulo', models.CharField(blank=True, max_length=40)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='categories.categoria')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='news.noticia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', '-criado_em'], name='analytics_e_tipo_59218f_idx')],
            },
        ),
    ]
