# Generated by Django 5.0.9 on 2026-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True, verbose_name='slug')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('cor', models.CharField(default='#1B48C4', max_length=7, verbose_name='cor (hex)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem no menu')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['nome'],
            },
        ),
    ]
