# Generated by Django 5.0.9 on 2026-09-20 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PUBLICACAO', 'Nova noticia'), ('CATEGORIA', 'Noticia de uma categoria seguida'), ('AUTOR', 'Noticia de um autor seguido'), ('URGENTE', 'Noticia urgente'), ('RESPOSTA', 'Resposta ao seu comentario'), ('SISTEMA', 'Aviso do sistema')], default='SISTEMA', max_length=12)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificacao',
                'verbose_name_plural': 'notificacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
