# Generated by Django 5.0.9 on 2026-09-20 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('interactions', '0001_initial'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorseguido',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autorseguido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_seguidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaseguida',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='categories.categoria'),
        ),
        migrations.AddField(
            model_name='categoriaseguida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_seguidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorito',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por', to='news.noticia'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historico',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='news.noticia'),
        ),
        migrations.AddField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagseguida',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='categories.tag'),
        ),
        migrations.AddField(
            model_name='tagseguida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_seguidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='autorseguido',
            unique_together={('usuario', 'autor')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriaseguida',
            unique_together={('usuario', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'noticia')},
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together={('usuario', 'noticia')},
        ),
        migrations.AlterUniqueTogether(
            name='tagseguida',
            unique_together={('usuario', 'tag')},
        ),
    ]
