# Generated by Django 5.0.9 on 2026-09-20 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=120, verbose_name='titulo')),
                ('posicao', models.CharField(choices=[('TOPO', 'Banner do topo'), ('LATERAL', 'Coluna lateral'), ('MATERIA', 'Dentro da materia'), ('FEED', 'Entre as noticias do feed')], db_index=True, max_length=8, verbose_name='posicao')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='imagem')),
                ('imagem_url', models.URLField(blank=True, verbose_name='imagem por URL')),
                ('url_destino', models.URLField(verbose_name='link de destino')),
                ('anunciante', models.CharField(blank=True, max_length=120, verbose_name='anunciante')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('impressoes', models.PositiveIntegerField(default=0, verbose_name='impressoes')),
                ('cliques', models.PositiveIntegerField(default=0, verbose_name='cliques')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['posicao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoAoVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=180, verbose_name='titulo')),
                ('conteudo', models.TextField(verbose_name='conteudo')),
                ('importante', models.BooleanField(default=False, verbose_name='destacar')),
                ('horario', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='horario')),
            ],
            options={
                'verbose_name': 'atualizacao ao vivo',
                'verbose_name_plural': 'atualizacoes ao vivo',
                'ordering': ['-horario'],
            },
        ),
        migrations.CreateModel(
            name='CoberturaAoVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('resumo', models.TextField(blank=True, max_length=400, verbose_name='resumo')),
                ('status', models.CharField(choices=[('AO_VIVO', 'Ao vivo'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada')], db_index=True, default='AO_VIVO', max_length=10, verbose_name='status')),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciada em')),
                ('encerrada_em', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
            ],
            options={
                'verbose_name': 'cobertura ao vivo',
                'verbose_name_plural': 'coberturas ao vivo',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='titulo')),
                ('url', models.URLField(blank=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'fonte',
                'verbose_name_plural': 'fontes',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('GALERIA', 'Item de galeria'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PODCAST', 'Podcast'), ('INFOGRAFICO', 'Infografico')], max_length=12, verbose_name='tipo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='midias/%Y/%m/', verbose_name='arquivo')),
                ('url', models.URLField(blank=True, verbose_name='url externa')),
                ('legenda', models.CharField(blank=True, max_length=250, verbose_name='legenda')),
                ('credito', models.CharField(blank=True, max_length=120, verbose_name='credito')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'midia',
                'verbose_name_plural': 'midias',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='subtitulo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('resumo', models.TextField(blank=True, max_length=500, verbose_name='resumo')),
                ('conteudo', models.TextField(verbose_name='conteudo')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='noticias/%Y/%m/', verbose_name='imagem principal')),
                ('imagem_url', models.URLField(blank=True, verbose_name='imagem por URL')),
                ('imagem_legenda', models.CharField(blank=True, max_length=250, verbose_name='legenda da imagem')),
                ('imagem_credito', models.CharField(blank=True, max_length=120, verbose_name='credito da imagem')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em revisao'), ('AGENDADA', 'Agendada'), ('PUBLICADA', 'Publicada'), ('ARQUIVADA', 'Arquivada')], db_index=True, default='RASCUNHO', max_length=10, verbose_name='status')),
                ('formato', models.CharField(choices=[('TEXTO', 'Materia'), ('GALERIA', 'Galeria'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PODCAST', 'Podcast'), ('INFOGRAFICO', 'Infografico'), ('AO_VIVO', 'Cobertura ao vivo')], default='TEXTO', max_length=12, verbose_name='formato')),
                ('destaque', models.BooleanField(db_index=True, default=False, verbose_name='destaque na home')),
                ('breaking_news', models.BooleanField(db_index=True, default=False, verbose_name='urgente')),
                ('exclusivo', models.BooleanField(default=False, verbose_name='conteudo exclusivo')),
                ('permitir_comentarios', models.BooleanField(default=True, verbose_name='permitir comentarios')),
                ('visualizacoes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='visualizacoes')),
                ('tempo_leitura', models.PositiveSmallIntegerField(default=1, verbose_name='tempo de leitura (min)')),
                ('data_publicacao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='data de publicacao')),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='ultima atualizacao editorial')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('plataforma', models.CharField(choices=[('INTERNO', 'Arquivo interno'), ('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo'), ('OUTRA', 'Outra')], default='YOUTUBE', max_length=8, verbose_name='plataforma')),
                ('url', models.URLField(blank=True, verbose_name='url do video')),
                ('id_externo', models.CharField(blank=True, max_length=60, verbose_name='id na plataforma')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/', verbose_name='arquivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/capas/', verbose_name='capa')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='capa por URL')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, verbose_name='duracao (s)')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='visualizacoes')),
                ('publicado', models.BooleanField(db_index=True, default=True, verbose_name='publicado')),
                ('publicado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='publicado em')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
