# Generated by Django 5.0.9 on 2026-09-20 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacaoaovivo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atualizacoes_ao_vivo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coberturaaovivo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to='categories.categoria'),
        ),
        migrations.AddField(
            model_name='coberturaaovivo',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atualizacaoaovivo',
            name='cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='news.coberturaaovivo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='categories.categoria', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='noticias', to='categories.tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='midia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='news.noticia'),
        ),
        migrations.AddField(
            model_name='fonte',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='news.noticia'),
        ),
        migrations.AddField(
            model_name='coberturaaovivo',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas', to='news.noticia', verbose_name='materia relacionada'),
        ),
        migrations.AddField(
            model_name='video',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='categories.categoria'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['status', '-data_publicacao'], name='news_notici_status_c9f62f_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categoria', '-data_publicacao'], name='news_notici_categor_6b26e2_idx'),
        ),
    ]
