# Generated by Django 5.0.9 on 2026-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('conteudo', models.TextField(max_length=2000, verbose_name='comentario')),
                ('status', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('PENDENTE', 'Aguardando moderacao'), ('OCULTO', 'Oculto'), ('REMOVIDO', 'Removido')], db_index=True, default='PUBLICADO', max_length=10, verbose_name='status')),
                ('editado', models.BooleanField(default=False, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CurtidaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curtida',
                'verbose_name_plural': 'curtidas',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('motivo', models.CharField(choices=[('SPAM', 'Spam'), ('OFENSIVO', 'Conteudo ofensivo'), ('DESINFORMACAO', 'Desinformacao'), ('OUTRO', 'Outro')], max_length=14)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('DESCARTADA', 'Descartada')], default='ABERTA', max_length=10)),
            ],
            options={
                'verbose_name': 'denuncia',
                'verbose_name_plural': 'denuncias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
